language: julia
os:
    - linux
julia:
    - 1.0
    - 1.1
    - 1.2
matrix:
    allow_failures:
        - julia: nightly
notifications:
    email: false
sudo: false
addons:
    apt_packages:
        - gfortran
        - liblapack-dev
        - libgmp-dev
        - libglpk-dev
after_success:
    - julia -e 'import Pkg; Pkg.add("Documenter")'
    - julia -e 'import Pkg; cd(Pkg.dir("Dualization")); include(joinpath("docs", "make.jl"))'
    # push coverage results to Codecov
    - julia --inline=no -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
env:
- CODECOV_TOKEN="4199e271-3fd5-4b25-ba53-e249bbe857f4"